---
language: node_js

node_js:
  - '0.10'

git:
   depth: 10

before_install:
  - npm install -qg bower gulp
  - npm install -q
  - bower install --force

script:
  - gulp test-src
  - ./node_modules/coveralls/bin/coveralls.js < coverage/lcov.info

